import { CarIcon, PersonIcon } from "../assets/icons";
import { ASSETS } from "./requireAssets";

export const ProductData = [
    {
        id: 1,
        name: "Aist qarorgohi",
        image: ASSETS.pr2,
        company: "Murad building",
        price: "35 000 $ dan",
        homeCount: "717 xonadon",
        process: "1-chorak 2023",
        near: "Karzinka.uz",
        nearTime: "20 daqiqa",
        studios: "48,4",
        twoRooms: "33,9",
        fourRoom: "62,7",
        oneRoom: "23,4",
        threeRoom: "47,2",
        fiveRoom: "0",
        contact: "+998 ( 99 ) 310 37 63",
        symbolDotIcon: <CarIcon />
    },
    {
        id: 2,
        name: "Aist qarorgohi",
        image: ASSETS.pr3,
        company: "Murad building",
        price: "35 000 $ dan",
        homeCount: "717 xonadon",
        process: "1-chorak 2023",
        near: "Karzinka.uz",
        nearTime: "20 daqiqa",
        studios: "48,4",
        twoRooms: "33,9",
        fourRoom: "62,7",
        oneRoom: "23,4",
        threeRoom: "47,2",
        fiveRoom: "0",
        contact: "+998 ( 99 ) 310 37 63",
        symbolDotIcon: <CarIcon />
    },
    {
        id: 3,
        name: "Aist qarorgohi",
        image: ASSETS.pr4,
        company: "Murad building",
        price: "35 000 $ dan",
        homeCount: "717 xonadon",
        process: "1-chorak 2023",
        near: "Karzinka.uz",
        nearTime: "20 daqiqa",
        studios: "48,4",
        twoRooms: "33,9",
        fourRoom: "62,7",
        oneRoom: "23,4",
        threeRoom: "47,2",
        fiveRoom: "0",
        contact: "+998 ( 99 ) 310 37 63",
        symbolDotIcon: <PersonIcon />
    },
    {
        id: 4,
        name: "Aist qarorgohi",
        image: ASSETS.pr4,
        company: "Murad building",
        price: "35 000 $ dan",
        homeCount: "717 xonadon",
        process: "1-chorak 2023",
        near: "Karzinka.uz",
        nearTime: "20 daqiqa",
        studios: "48,4",
        twoRooms: "33,9",
        fourRoom: "62,7",
        oneRoom: "23,4",
        threeRoom: "47,2",
        fiveRoom: "0",
        contact: "+998 ( 99 ) 310 37 63",
        symbolDotIcon: <PersonIcon />
    },
    {
        id: 5,
        name: "Aist qarorgohi",
        image: ASSETS.pr4,
        company: "Murad building",
        price: "35 000 $ dan",
        homeCount: "717 xonadon",
        process: "1-chorak 2023",
        near: "Karzinka.uz",
        nearTime: "20 daqiqa",
        studios: "48,4",
        twoRooms: "33,9",
        fourRoom: "62,7",
        oneRoom: "23,4",
        threeRoom: "47,2",
        fiveRoom: "0",
        contact: "+998 ( 99 ) 310 37 63",
        symbolDotIcon: <PersonIcon />
    },
    {
        id: 6,
        name: "Aist qarorgohi",
        image: ASSETS.pr4,
        company: "Murad building",
        price: "35 000 $ dan",
        homeCount: "717 xonadon",
        process: "1-chorak 2023",
        near: "Karzinka.uz",
        nearTime: "20 daqiqa",
        studios: "48,4",
        twoRooms: "33,9",
        fourRoom: "62,7",
        oneRoom: "23,4",
        threeRoom: "47,2",
        fiveRoom: "0",
        contact: "+998 ( 99 ) 310 37 63",
        symbolDotIcon: <PersonIcon />
    },
    {
        id: 7,
        name: "Aist qarorgohi",
        image: ASSETS.pr4,
        company: "Murad building",
        price: "35 000 $ dan",
        homeCount: "717 xonadon",
        process: "1-chorak 2023",
        near: "Karzinka.uz",
        nearTime: "20 daqiqa",
        studios: "48,4",
        twoRooms: "33,9",
        fourRoom: "62,7",
        oneRoom: "23,4",
        threeRoom: "47,2",
        fiveRoom: "0",
        contact: "+998 ( 99 ) 310 37 63",
        symbolDotIcon: <PersonIcon />
    },
]